### ISSUE TITLE
DFA example files corrupt

### ISSUE THREAD

**Issue by hyblocker** [CMDJojo/dandy#1]
The DFAs in the example folder `dandy/benches/example_dfas` seem to be corrupt and invalid. I can't tell whether or not this is intentional, but if not, it seems that the files may be getting corrupted upon committing.

**Comment by CMDJojo** [comment]
Thank you for your issue!
The examples are, in fact, not corrupt or invalid. The parser accepts any unicode string without reserved characters as a name, and thus the example does compile with `dandy`. The examples were generated with `proptest` and have thus already passed the parser, compiler and checker before appearing in that folder. But your comment made me aware of that it would probably be better to have some examples with just ascii names to make them more readable. Will replace them very soon and reply here with the commit. Thanks for your input!

**Comment by CMDJojo** [comment]
Example DFAs changes as of a1f8402b415c94c64df2fd3f468b16cc06f84a3f .
